export enum ClientStatus {
  PENDING = 'PENDING',
  INTERESTED = 'INTERESTED',
  CONVERTED = 'CONVERTED',
  REJECTED = 'REJECTED',
  INVALID_NUMBER = 'INVALID_NUMBER',
  DO_NOT_CALL = 'DO_NOT_CALL',
}
